# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addadmin.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

class Ui_addadmin(object):
    def setupUi(self, addadmin):
        addadmin.setObjectName("addadmin")
        addadmin.resize(846, 600)
        font = QtGui.QFont()
        font.setPointSize(18)
        addadmin.setFont(font)
        self.centralwidget = QtWidgets.QWidget(addadmin)
        self.centralwidget.setObjectName("centralwidget")
        self.l1 = QtWidgets.QLabel(self.centralwidget)
        self.l1.setGeometry(QtCore.QRect(40, 30, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(19)
        self.l1.setFont(font)
        self.l1.setObjectName("l1")
        self.l2 = QtWidgets.QLabel(self.centralwidget)
        self.l2.setGeometry(QtCore.QRect(40, 80, 141, 31))
        self.l2.setObjectName("l2")
        self.l3 = QtWidgets.QLabel(self.centralwidget)
        self.l3.setGeometry(QtCore.QRect(40, 120, 121, 31))
        self.l3.setObjectName("l3")
        self.l4 = QtWidgets.QLabel(self.centralwidget)
        self.l4.setGeometry(QtCore.QRect(40, 170, 231, 31))
        self.l4.setObjectName("l4")
        self.l5 = QtWidgets.QLabel(self.centralwidget)
        self.l5.setGeometry(QtCore.QRect(40, 220, 271, 41))
        self.l5.setObjectName("l5")
        self.line1 = QtWidgets.QLineEdit(self.centralwidget)
        self.line1.setGeometry(QtCore.QRect(300, 30, 361, 31))
        self.line1.setObjectName("line1")
        self.line2 = QtWidgets.QLineEdit(self.centralwidget)
        self.line2.setGeometry(QtCore.QRect(300, 80, 361, 31))
        self.line2.setObjectName("line2")
        self.line3 = QtWidgets.QLineEdit(self.centralwidget)
        self.line3.setGeometry(QtCore.QRect(300, 120, 361, 31))
        self.line3.setObjectName("line3")
        self.line4 = QtWidgets.QLineEdit(self.centralwidget)
        self.line4.setGeometry(QtCore.QRect(300, 170, 371, 31))
        self.line4.setEchoMode(QtWidgets.QLineEdit.Password)
        self.line4.setObjectName("line4")
        self.line5 = QtWidgets.QLineEdit(self.centralwidget)
        self.line5.setGeometry(QtCore.QRect(300, 220, 371, 31))
        self.line5.setEchoMode(QtWidgets.QLineEdit.Password)
        self.line5.setObjectName("line5")
        self.b1 = QtWidgets.QPushButton(self.centralwidget)
        self.b1.setGeometry(QtCore.QRect(260, 320, 171, 51))
        self.b1.setObjectName("b1")

        self.b1.clicked.connect(self.register)

        addadmin.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(addadmin)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 846, 47))
        self.menubar.setObjectName("menubar")
        addadmin.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(addadmin)
        self.statusbar.setObjectName("statusbar")
        addadmin.setStatusBar(self.statusbar)

        self.retranslateUi(addadmin)
        QtCore.QMetaObject.connectSlotsByName(addadmin)

    def retranslateUi(self, addadmin):
        _translate = QtCore.QCoreApplication.translate
        addadmin.setWindowTitle(_translate("addadmin", "MainWindow"))
        self.l1.setText(_translate("addadmin", "Name"))
        self.l2.setText(_translate("addadmin", "Phone No"))
        self.l3.setText(_translate("addadmin", "Email ID"))
        self.l4.setText(_translate("addadmin", "Enter Password"))
        self.l5.setText(_translate("addadmin", "Re Enter Password"))
        self.b1.setText(_translate("addadmin", "Register"))

    def register(self):
        import sqlite3
        conn=sqlite3.connect("dms.db")
        cur=conn.cursor()
        a=self.line1.text()
        b=self.line2.text()
        c=self.line3.text()
        d=self.line4.text()
        e=self.line5.text()
        if(a==""):
            print("1")
        elif(b==""):
            print("2")
        elif(b.isdigit()==False):
             print("3")
        elif len(b)!=10:
            print("4")
        elif(c==""):
            print("5")
        elif(d==""):
            print("6")
        elif len(d)<8 or len(d)>15: 
            print("7")
        elif(e==""):
            print("8")
        elif len(e)<8 or len(e)>15:
            print("10")
        elif(d!=e):
            print("9")
        

        else:
            sql = "select count(*) from admin where Eid = ? or phno = ?"
            v1 = (c, b)  
            cur.execute(sql, v1)
            conn.commit()
            result = cur.fetchall()
            rc = result[0][0] 
            if rc > 0: 
                print("Email ID or Phone number already exists")
            else:
                sql = "insert into admin values(?,?,?,?)"
                v2 = (a, b, c, d,)
                cur.execute(sql, v2)  
                conn.commit() 
                rc = cur.rowcount 
                
                print("Admin registered successfully")
        conn.close()
                    
                



       
            
        
        '''x=(a,b,c,d)

        sql="insert into admin values(?, ?, ?, ? )"
        cur.execute(sql,x)
        conn.commit()
        rc=cur.rowcount
        if(rc==1):
            msg=QMessageBox()
            msg.setIcon(QMessageBox.Critical)
            msg.setText("add")
            msg.setWindowTitle("Login Error")
            msg.show()
            retval=msg.exec_()
        else:
            msg=QMessageBox()
            msg.setIcon(QMessageBox.Critical)
            msg.setText("add")
            msg.setWindowTitle("register")
            msg.show()
            retval=msg.exec_()'''
       
      




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    addadmin = QtWidgets.QMainWindow()
    ui = Ui_addadmin()
    ui.setupUi(addadmin)
    addadmin.show()
    sys.exit(app.exec_())
