# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adddebt.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from deptupdate  import*
from PyQt5.QtWidgets import QMessageBox
class Ui_adddebt(object):
    
    def setupUi(self, adddebt):
        adddebt.setObjectName("adddebt")
        adddebt.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(adddebt)
        self.centralwidget.setObjectName("centralwidget")
        self.l1 = QtWidgets.QLabel(self.centralwidget)
        self.l1.setGeometry(QtCore.QRect(100, 60, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.l1.setFont(font)
        self.l1.setObjectName("l1")
        self.t1 = QtWidgets.QLineEdit(self.centralwidget)
        self.t1.setGeometry(QtCore.QRect(310, 70, 391, 31))
        self.t1.setObjectName("t1")
        self.b1 = QtWidgets.QPushButton(self.centralwidget)
        self.b1.setGeometry(QtCore.QRect(290, 140, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.b1.setFont(font)
        self.b1.setObjectName("b1")

        self.b1.clicked.connect(self.add)

        self.adddept = QtWidgets.QTableWidget(self.centralwidget)
        self.adddept.setGeometry(QtCore.QRect(180, 200, 341, 192))
        self.adddept.setObjectName("adddept")
        self.adddept.setColumnCount(1)
        self.adddept.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.adddept.setHorizontalHeaderItem(0, item)
        self.b2 = QtWidgets.QPushButton(self.centralwidget)
        self.b2.setGeometry(QtCore.QRect(160, 430, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.b2.setFont(font)
        self.b2.setObjectName("b2")

        self.b2.clicked.connect(self.edit)

        self.b3 = QtWidgets.QPushButton(self.centralwidget)
        self.b3.setGeometry(QtCore.QRect(370, 430, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.b3.setFont(font)
        self.b3.setObjectName("b3")

        self.b3.clicked.connect(self.delete)

        adddebt.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(adddebt)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        adddebt.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(adddebt)
        self.statusbar.setObjectName("statusbar")
        adddebt.setStatusBar(self.statusbar)

        self.retranslateUi(adddebt)
        QtCore.QMetaObject.connectSlotsByName(adddebt)
        self.show()
    def retranslateUi(self, adddebt):
        _translate = QtCore.QCoreApplication.translate
        adddebt.setWindowTitle(_translate("adddebt", "MainWindow"))
        self.l1.setText(_translate("adddebt", "Department Name"))
        self.b1.setText(_translate("adddebt", "ADD"))
        item = self.adddept.horizontalHeaderItem(0)
        item.setText(_translate("adddebt", "Dept Name"))
        self.b2.setText(_translate("adddebt", "Edit"))
        self.b3.setText(_translate("adddebt", "Delete"))
    
    def show(self):
        self.adddept.setRowCount(0) 
        import sqlite3
        conn = sqlite3.connect("dms.db")
        cur = conn.cursor()
        sql = "select * from deptupdatetable"
        res = cur.execute(sql)
        r = res.fetchall()
        for i in r:
            n = i[0]
            rc = self.adddept.rowCount()  
            self.adddept.insertRow(rc) 
            self.adddept.setItem(rc, 0, QtWidgets.QTableWidgetItem(n))  
        conn.commit()
        conn.close()

    def add(self):
        import sqlite3
        conn = sqlite3.connect("dms.db")
        cur = conn.cursor()
        x = self.t1.text()
        v = (x,)
        sql = "select count(*) from deptupdatetable  where Name=?"
        res = cur.execute(sql, v)
        r = res.fetchall()
        if r[0][0] == 0:
            v = (x,)
            sql = "insert into deptupdatetable values(?)"
            cur.execute(sql, v)
            conn.commit()
            c = cur.rowcount
            if c == 1:
                msg = QMessageBox()
                msg.setIcon(QMessageBox.Critical)
                msg.setText("Addept")
                msg.setWindowTitle("Add Department")
                msg.exec_()
            else:
                msg = QMessageBox()
                msg.setText("Not added")
                msg.exec_()
            conn.close()
        else:
            print("Department already exists")

    def edit(self):
        Index=self.adddept.currentIndex()
        row=Index.row()
        x=self.adddept.item(row,0)
        n=x.text()
        self.depttableupdate = QtWidgets.QMainWindow()  
        self.ui = Ui_deptupdate(x) 
        self.ui.setupUi(self.depttableupdate)
        self.depttableupdate.show()

    def delete(self):
        Index=self.adddept.currentIndex()
        row=Index.row()
        x=self.adddept.item(row,0)
        n=x.text()
        import sqlite3
        conn = sqlite3.connect("dms.db")
        cur = conn.cursor()
        v = (n,)
        sql = "delete from deptupdatetable where Name=?"
        cur.execute(sql, v)
        conn.commit()
        c = cur.rowcount
        if c >=1:
            print("Deleted")
        else:
            print("Not deleted")
        conn.close()


        

    
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    adddebt = QtWidgets.QMainWindow()
    ui = Ui_adddebt()
    ui.setupUi(adddebt)
    adddebt.show()
    sys.exit(app.exec_())
