# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adddoctor.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox

class Ui_adddoctor(object):
    def setupUi(self, adddoctor):
        adddoctor.setObjectName("adddoctor")
        adddoctor.resize(822, 635)
        self.centralwidget = QtWidgets.QWidget(adddoctor)
        self.centralwidget.setObjectName("centralwidget")
        self.l1 = QtWidgets.QLabel(self.centralwidget)
        self.l1.setGeometry(QtCore.QRect(90, 20, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.l1.setFont(font)
        self.l1.setObjectName("l1")
        self.l2 = QtWidgets.QLabel(self.centralwidget)
        self.l2.setGeometry(QtCore.QRect(90, 80, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.l2.setFont(font)
        self.l2.setObjectName("l2")
        self.l3 = QtWidgets.QLabel(self.centralwidget)
        self.l3.setGeometry(QtCore.QRect(90, 150, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.l3.setFont(font)
        self.l3.setObjectName("l3")
        self.l4 = QtWidgets.QLabel(self.centralwidget)
        self.l4.setGeometry(QtCore.QRect(90, 230, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.l4.setFont(font)
        self.l4.setObjectName("l4")
        self.l5 = QtWidgets.QLabel(self.centralwidget)
        self.l5.setGeometry(QtCore.QRect(90, 310, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.l5.setFont(font)
        self.l5.setObjectName("l5")
        self.l6 = QtWidgets.QLabel(self.centralwidget)
        self.l6.setGeometry(QtCore.QRect(90, 390, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.l6.setFont(font)
        self.l6.setObjectName("l6")
        self.t1 = QtWidgets.QLineEdit(self.centralwidget)
        self.t1.setGeometry(QtCore.QRect(290, 20, 381, 41))
        self.t1.setObjectName("t1")
        self.t2 = QtWidgets.QLineEdit(self.centralwidget)
        self.t2.setGeometry(QtCore.QRect(290, 90, 381, 41))
        self.t2.setObjectName("t2")
        self.t4 = QtWidgets.QLineEdit(self.centralwidget)
        self.t4.setGeometry(QtCore.QRect(290, 310, 381, 41))
        self.t4.setObjectName("t4")
        self.t3 = QtWidgets.QLineEdit(self.centralwidget)
        self.t3.setGeometry(QtCore.QRect(290, 160, 381, 41))
        self.t3.setObjectName("t3")
        self.t5 = QtWidgets.QLineEdit(self.centralwidget)
        self.t5.setGeometry(QtCore.QRect(290, 390, 381, 41))
        self.t5.setObjectName("t5")
        self.combo1 = QtWidgets.QComboBox(self.centralwidget)
        self.combo1.setGeometry(QtCore.QRect(290, 230, 381, 41))
        self.combo1.setObjectName("combo1")
        self.b1 = QtWidgets.QPushButton(self.centralwidget)
        self.b1.setGeometry(QtCore.QRect(330, 480, 121, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.b1.setFont(font)
        self.b1.setObjectName("b1")

        self.b1.clicked.connect(self.add)

        
        adddoctor.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(adddoctor)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 822, 26))
        self.menubar.setObjectName("menubar")
        adddoctor.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(adddoctor)
        self.statusbar.setObjectName("statusbar")
        adddoctor.setStatusBar(self.statusbar)

        self.retranslateUi(adddoctor)
        QtCore.QMetaObject.connectSlotsByName(adddoctor)
        self.show()

    def retranslateUi(self, adddoctor):
        _translate = QtCore.QCoreApplication.translate
        adddoctor.setWindowTitle(_translate("adddoctor", "MainWindow"))
        self.l1.setText(_translate("adddoctor", "NAME"))
        self.l2.setText(_translate("adddoctor", "EMAIL"))
        self.l3.setText(_translate("adddoctor", "PHONE NO"))
        self.l4.setText(_translate("adddoctor", "DEPT"))
        self.l5.setText(_translate("adddoctor", "PASSWORD"))
        self.l6.setText(_translate("adddoctor", "RE PASSWORD"))
        self.b1.setText(_translate("adddoctor", "ADD"))

    def show(self):
        import sqlite3
        conn = sqlite3.connect("dms.db")
        cur = conn.cursor()
        sql = "SELECT Name FROM deptupdatetable"
        cur.execute(sql) 
        dept = cur.fetchall() 
        self.combo1.clear()
        print(dept)
        for department in dept:
            self.combo1.addItem(department[0])
        conn.close()

    def add(self):
        import sqlite3
        conn = sqlite3.connect("dms.db")
        cur = conn.cursor()
        a= self.t1.text()
        b= self.t2.text()
        c= self.t3.text()
        d= self.t4.text()

        dept=self.combo1.currentText()
        v = (a,b,c,d)
        sql = "select count(*) from adddoctor  where name=? or Eid=? or phno=? or password=?"
        res = cur.execute(sql, v)
        r = res.fetchall()
        if r[0][0] == 0:
            v = (a,b,c,d,dept)

            sql = "insert into adddoctor values(?,?,?,?,?)"
            cur.execute(sql, v)
            conn.commit()
            c = cur.rowcount
            if c == 1:
                msg = QMessageBox()
                msg.setIcon(QMessageBox.Critical)
                msg.setText("Adddoctor")
                msg.setWindowTitle("Add Doctor")
                msg.exec_()
            else:
                msg = QMessageBox()
                msg.setText("Not added")
                msg.exec_()
            conn.close()
        else:
            print("Doctor already exists")

        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    adddoctor = QtWidgets.QMainWindow()
    ui = Ui_adddoctor()
    ui.setupUi(adddoctor)
    adddoctor.show()
    sys.exit(app.exec_())
