# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'allbooking.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_allbooking(object):
    def setupUi(self, allbooking):
        allbooking.setObjectName("allbooking")
        allbooking.resize(1054, 836)
        self.centralwidget = QtWidgets.QWidget(allbooking)
        self.centralwidget.setObjectName("centralwidget")
        self.allbooking_2 = QtWidgets.QTableWidget(self.centralwidget)
        self.allbooking_2.setGeometry(QtCore.QRect(60, 80, 821, 401))
        self.allbooking_2.setObjectName("allbooking_2")
        self.allbooking_2.setColumnCount(6)
        self.allbooking_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.allbooking_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.allbooking_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.allbooking_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.allbooking_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.allbooking_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.allbooking_2.setHorizontalHeaderItem(5, item)
        allbooking.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(allbooking)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1054, 26))
        self.menubar.setObjectName("menubar")
        allbooking.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(allbooking)
        self.statusbar.setObjectName("statusbar")
        allbooking.setStatusBar(self.statusbar)
        self.retranslateUi(allbooking)
        QtCore.QMetaObject.connectSlotsByName(allbooking)
        self.display()
    def retranslateUi(self, allbooking):
        _translate = QtCore.QCoreApplication.translate
        allbooking.setWindowTitle(_translate("allbooking", "MainWindow"))
        item = self.allbooking_2.horizontalHeaderItem(0)
        item.setText(_translate("allbooking", "PID"))
        item = self.allbooking_2.horizontalHeaderItem(1)
        item.setText(_translate("allbooking", "NAME"))
        item = self.allbooking_2.horizontalHeaderItem(2)
        item.setText(_translate("allbooking", "PHNO"))
        item = self.allbooking_2.horizontalHeaderItem(3)
        item.setText(_translate("allbooking", "DOCTORNAME"))
        item = self.allbooking_2.horizontalHeaderItem(4)
        item.setText(_translate("allbooking", "SYMPTOM"))
        item = self.allbooking_2.horizontalHeaderItem(5)
        item.setText(_translate("allbooking", "DATE"))
    def display(self):
        import sqlite3
        conn = sqlite3.connect("dms.db")
        cur = conn.cursor()
        sql="select * from booking"
        cur.execute(sql)
        data=cur.fetchall()
        print(data)
        for i in data:
            pid=i[0]
            sqlp="select * from patient where pid=?"
            cur.execute(sqlp,(pid,))
            datap=cur.fetchall()
            n=datap[0][1]
            p=datap[0][2]
            doctor=i[1]
            symptom=i[2]
            date=i[3]

            rowPosition = self.allbooking_2.rowCount()
            self.allbooking_2.insertRow(rowPosition)
            self.allbooking_2.setItem(rowPosition, 0, QtWidgets.QTableWidgetItem(str(pid)))
            self.allbooking_2.setItem(rowPosition, 1, QtWidgets.QTableWidgetItem(n))
            self.allbooking_2.setItem(rowPosition, 2, QtWidgets.QTableWidgetItem(p))
            self.allbooking_2.setItem(rowPosition, 3, QtWidgets.QTableWidgetItem(doctor))
            self.allbooking_2.setItem(rowPosition, 4, QtWidgets.QTableWidgetItem(symptom))
            self.allbooking_2.setItem(rowPosition, 5, QtWidgets.QTableWidgetItem(date))
        conn.close()
        
        

       
        




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    allbooking = QtWidgets.QMainWindow()
    ui = Ui_allbooking()
    ui.setupUi(allbooking)
    allbooking.show()
    sys.exit(app.exec_())
