# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'deptupdate.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sqlite3
class Ui_deptupdate(object):
    def __init__(self,x):
            self.name=x
    def setupUi(self, deptupdate):
        deptupdate.setObjectName("deptupdate")
        deptupdate.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(deptupdate)
        self.centralwidget.setObjectName("centralwidget")
        self.l1 = QtWidgets.QLabel(self.centralwidget)
        self.l1.setGeometry(QtCore.QRect(160, 60, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.l1.setFont(font)
        self.l1.setObjectName("l1")
        self.t1 = QtWidgets.QLineEdit(self.centralwidget)
        self.t1.setGeometry(QtCore.QRect(410, 70, 231, 31))
        self.t1.setObjectName("t1")
        self.b1 = QtWidgets.QPushButton(self.centralwidget)
        self.b1.setGeometry(QtCore.QRect(330, 160, 93, 28))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.b1.setFont(font)
        self.b1.setObjectName("b1")

        self.b1.clicked.connect(self.update)

        deptupdate.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(deptupdate)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        deptupdate.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(deptupdate)
        self.statusbar.setObjectName("statusbar")
        deptupdate.setStatusBar(self.statusbar)

        self.retranslateUi(deptupdate)
        QtCore.QMetaObject.connectSlotsByName(deptupdate)

    def retranslateUi(self, deptupdate):
        _translate = QtCore.QCoreApplication.translate
        deptupdate.setWindowTitle(_translate("deptupdate", "MainWindow"))
        self.l1.setText(_translate("deptupdate", "Department Name"))
        self.b1.setText(_translate("deptupdate", "Update"))

    def update(self):
        x = self.t1.text()
        if x:
            conn = sqlite3.connect("dms.db")
            cur = conn.cursor()
            sql = "UPDATE deptupdatetable SET Name = ? where name"  
            v = (x,)
            cur.execute(sql, v)
            conn.commit()
            c = cur.rowcount
            if c == 1:
                print("Updated")
            else:
                print("Not updated")
            conn.close()
        else:
            print("Department name cannot be empty")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    deptupdate = QtWidgets.QMainWindow()
    ui = Ui_deptupdate()
    ui.setupUi(deptupdate)
    deptupdate.show()
    sys.exit(app.exec_())