# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'patient.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from allbooking import *

class Ui_patient(object):
    def setupUi(self, patient):
        patient.setObjectName("patient")
        patient.resize(1099, 864)
        font = QtGui.QFont()
        font.setPointSize(14)
        patient.setFont(font)
        self.centralwidget = QtWidgets.QWidget(patient)
        self.centralwidget.setObjectName("centralwidget")
        self.l1 = QtWidgets.QLabel(self.centralwidget)
        self.l1.setGeometry(QtCore.QRect(130, 30, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.l1.setFont(font)
        self.l1.setObjectName("l1")
        self.t1 = QtWidgets.QLineEdit(self.centralwidget)
        self.t1.setGeometry(QtCore.QRect(580, 40, 381, 41))
        self.t1.setObjectName("t1")
        self.b1 = QtWidgets.QPushButton(self.centralwidget)
        self.b1.setGeometry(QtCore.QRect(480, 110, 111, 28))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.b1.setFont(font)
        self.b1.setObjectName("b1")

        self.b1.clicked.connect(self.search)

        self.l2 = QtWidgets.QLabel(self.centralwidget)
        self.l2.setGeometry(QtCore.QRect(230, 160, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.l2.setFont(font)
        self.l2.setObjectName("l2")
        self.l3 = QtWidgets.QLabel(self.centralwidget)
        self.l3.setGeometry(QtCore.QRect(830, 150, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.l3.setFont(font)
        self.l3.setObjectName("l3")
        self.l4 = QtWidgets.QLabel(self.centralwidget)
        self.l4.setGeometry(QtCore.QRect(220, 210, 121, 21))
        self.l4.setObjectName("l4")
        self.l5 = QtWidgets.QLabel(self.centralwidget)
        self.l5.setGeometry(QtCore.QRect(220, 260, 131, 21))
        self.l5.setObjectName("l5")
        self.l6 = QtWidgets.QLabel(self.centralwidget)
        self.l6.setGeometry(QtCore.QRect(220, 300, 121, 31))
        self.l6.setObjectName("l6")
        self.l7 = QtWidgets.QLabel(self.centralwidget)
        self.l7.setGeometry(QtCore.QRect(220, 350, 131, 41))
        self.l7.setObjectName("l7")
        self.l8 = QtWidgets.QLabel(self.centralwidget)
        self.l8.setGeometry(QtCore.QRect(220, 410, 121, 31))
        self.l8.setObjectName("l8")
        self.l9 = QtWidgets.QLabel(self.centralwidget)
        self.l9.setGeometry(QtCore.QRect(220, 460, 171, 31))
        self.l9.setObjectName("l9")
        self.l10 = QtWidgets.QLabel(self.centralwidget)
        self.l10.setGeometry(QtCore.QRect(220, 510, 141, 21))
        self.l10.setObjectName("l10")
        self.l11 = QtWidgets.QLabel(self.centralwidget)
        self.l11.setGeometry(QtCore.QRect(220, 560, 151, 21))
        self.l11.setObjectName("l11")
        self.l12 = QtWidgets.QLabel(self.centralwidget)
        self.l12.setGeometry(QtCore.QRect(220, 610, 261, 31))
        self.l12.setObjectName("l12")
        self.l13 = QtWidgets.QLabel(self.centralwidget)
        self.l13.setGeometry(QtCore.QRect(220, 670, 181, 31))
        self.l13.setObjectName("l13")
        self.t2 = QtWidgets.QLineEdit(self.centralwidget)
        self.t2.setGeometry(QtCore.QRect(700, 190, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.t2.setFont(font)
        self.t2.setObjectName("t2")
        self.b2 = QtWidgets.QPushButton(self.centralwidget)
        self.b2.setGeometry(QtCore.QRect(480, 740, 131, 28))
        self.b2.setObjectName("b2")

        self.b2.clicked.connect(self.booking)


        self.t3 = QtWidgets.QLineEdit(self.centralwidget)
        self.t3.setGeometry(QtCore.QRect(700, 240, 351, 31))
        self.t3.setObjectName("t3")
        self.t4 = QtWidgets.QLineEdit(self.centralwidget)
        self.t4.setGeometry(QtCore.QRect(700, 290, 351, 31))
        self.t4.setObjectName("t4")
        self.t5 = QtWidgets.QLineEdit(self.centralwidget)
        self.t5.setGeometry(QtCore.QRect(700, 350, 361, 31))
        self.t5.setObjectName("t5")
        self.r1 = QtWidgets.QRadioButton(self.centralwidget)
        self.r1.setGeometry(QtCore.QRect(690, 410, 95, 20))
        self.r1.setObjectName("r1")
        self.r2 = QtWidgets.QRadioButton(self.centralwidget)
        self.r2.setGeometry(QtCore.QRect(790, 410, 121, 20))
        self.r2.setObjectName("r2")
        self.r3 = QtWidgets.QRadioButton(self.centralwidget)
        self.r3.setGeometry(QtCore.QRect(920, 410, 121, 20))
        self.r3.setObjectName("r3")
        self.combo1 = QtWidgets.QComboBox(self.centralwidget)
        self.combo1.setGeometry(QtCore.QRect(700, 460, 361, 31))
        self.combo1.setObjectName("combo1")
        self.combo2 = QtWidgets.QComboBox(self.centralwidget)
        self.combo2.setGeometry(QtCore.QRect(700, 510, 361, 31))
        self.combo2.setObjectName("combo2")

        self.combo1.currentIndexChanged.connect(self.doc)

        self.t6 = QtWidgets.QLineEdit(self.centralwidget)
        self.t6.setGeometry(QtCore.QRect(700, 560, 361, 31))
        self.t6.setObjectName("t6")
        self.t7 = QtWidgets.QLineEdit(self.centralwidget)
        self.t7.setGeometry(QtCore.QRect(700, 610, 361, 31))
        self.t7.setObjectName("t7")
        self.combo3 = QtWidgets.QComboBox(self.centralwidget)
        self.combo3.setGeometry(QtCore.QRect(700, 670, 361, 31))
        self.combo3.setObjectName("combo3")
        patient.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(patient)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1099, 37))
        self.menubar.setObjectName("menubar")
        patient.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(patient)
        self.statusbar.setObjectName("statusbar")
        patient.setStatusBar(self.statusbar)

        self.retranslateUi(patient)
        QtCore.QMetaObject.connectSlotsByName(patient)
        self.show()
    def retranslateUi(self, patient):
        _translate = QtCore.QCoreApplication.translate
        patient.setWindowTitle(_translate("patient", "MainWindow"))
        self.l1.setText(_translate("patient", "Enter Patient Phone No"))
        self.b1.setText(_translate("patient", "SEARCH"))
        self.l2.setText(_translate("patient", "PID"))
        self.l3.setText(_translate("patient", ""))
        self.l4.setText(_translate("patient", "NAME"))
        self.l5.setText(_translate("patient", "PHONE NO"))
        self.l6.setText(_translate("patient", "EMAIL"))
        self.l7.setText(_translate("patient", "ADDRESS"))
        self.l8.setText(_translate("patient", "GENDER"))
        self.l9.setText(_translate("patient", "DEPARTMENT"))
        self.l10.setText(_translate("patient", "DOCTORS"))
        self.l11.setText(_translate("patient", "SYMPTOM"))
        self.l12.setText(_translate("patient", "DATE OF ADDMISSION"))
        self.l13.setText(_translate("patient", "BLOOD GROUP"))
        self.b2.setText(_translate("patient", "BOOK"))
        self.r1.setText(_translate("patient", "MALE"))
        self.r2.setText(_translate("patient", "FEMALE"))
        self.r3.setText(_translate("patient", "OTHERS"))

    
    def show(self):
        import sqlite3
        conn = sqlite3.connect("dms.db")
        cur = conn.cursor()
        sql = "SELECT Name FROM deptupdatetable"
        cur.execute(sql) 
        dept = cur.fetchall() 
        self.combo1.clear()
        for department in dept:
            self.combo1.addItem(department[0])
        v=['A','B']
        self.combo3.clear()
        self.combo3.addItem("Select Blood Group")
        for i in v:
            self.combo3.addItem(i)
        conn.close()

    def doc(self):
        import sqlite3
        conn = sqlite3.connect("dms.db")
        cur = conn.cursor()
        doctor=self.combo1.currentText()
        v=(doctor,)
        sql = "SELECT Name FROM adddoctor where dept=?"
        cur.execute(sql,v) 
        
        doctor = cur.fetchall() 
        self.combo2.clear()
        print(doctor)
        for doctors in doctor:
            self.combo2.addItem(doctors[0])
        conn.close()

    def search(self):
        import sqlite3
        conn=sqlite3.connect("dms.db")
        cur=conn.cursor()
        phno1=self.t1.text()
        sql="SELECT * From patient where phno =?"
        cur.execute(sql,(phno1,)) 
        phno=cur.fetchall() 
        c=len(phno) 
        if c>0:
            self.l3.setText(str(phno[0][0]))
            self.t2.setText(phno[0][1])
            self.t3.setText(phno[0][2])
            self.t4.setText(phno[0][3])
            self.t5.setText(phno[0][4])
            g=phno[0][5]
            if g=="Male":
                self.r1.setChecked(True)
                self.r2.setChecked(False)
                self.r3.setChecked(False)
            elif g=="Female":
                self.r1.setChecked(False)
                self.r2.setChecked(True)
                self.r3.setChecked(False)
            else:
                self.r1.setChecked(False)
                self.r2.setChecked(False)
                self.r3.setChecked(True)
            self.combo3.clear()
            self.combo3.addItem(phno[0][6])
            
        else:
            self.t3.setText(self.t1.text())
            self.t1.setText("patient phone not found ")
            
        conn.close()

    
    def booking(self):
        name=self.t2.text()
        phno=self.t3.text()
        Eid=self.t4.text()
        Address=self.t5.text()
       
        if self.r1.isChecked():
            gender="Male" 
        elif  self.r2.isChecked():
            gender="Female"

        else:
            gender="Others"
            
        #department=self.combo1.currentText()
        doctor=self.combo2.currentText()
        system=self.t6.text()
        date= self.t7.text()
        bloodgroup = self.combo3.currentText()
        pid=0
        import sqlite3
        conn=sqlite3.connect("dms.db")
        cur=conn.cursor()
        sql="SELECT * From patient"
        cur.execute(sql) 
        phvalue=cur.fetchall() 
        c=len(phvalue) 
        if c==0:
            pid=1000;
            patientdata = (pid,name,phno, Eid, Address, gender, bloodgroup)
            patient = "INSERT INTO patient  VALUES (?,?, ?, ?, ?, ?, ?)"
        
            cur.execute(patient,patientdata)
            conn.commit() 
        else:
            
            phno=self.t3.text()
            sql="SELECT * From patient where phno =?"
            cur.execute(sql,(phno,)) 
            res=cur.fetchall() 
            c1=len(res)
            if(c1>0):
                pid=int(res[0][0])
            else:
                sqlpid="SELECT * From patient order by pid desc limit 1"
                cur.execute(sqlpid);
                ph=cur.fetchall() 
                pid=int(ph[0][0])+1
                patientdata = (pid,name,phno, Eid, Address, gender, bloodgroup)
                patient = "INSERT INTO patient  VALUES (?,?, ?, ?, ?, ?, ?)"
                cur.execute(patient,patientdata)
                conn.commit() 
        
        

        

       
        bookingdata = (pid, doctor,system,date)
        booking ="INSERT INTO booking  VALUES (?, ?, ?, ?)"
        cur.execute(booking,bookingdata)  
        conn.commit() 
        conn.close()
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    patient = QtWidgets.QMainWindow()
    ui = Ui_patient()
    ui.setupUi(patient)
    patient.show()
    sys.exit(app.exec_())
