# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pescribe.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from datetime import*


class Ui_pescribe(object):
    def __init__(self, pid):
        self.p = pid
    def setupUi(self, pescribe):
        pescribe.setObjectName("pescribe")
        pescribe.resize(1117, 724)
        self.centralwidget = QtWidgets.QWidget(pescribe)
        self.centralwidget.setObjectName("centralwidget")
        self.l1 = QtWidgets.QLabel(self.centralwidget)
        self.l1.setGeometry(QtCore.QRect(100, 70, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.l1.setFont(font)
        self.l1.setObjectName("l1")
        self.l2 = QtWidgets.QLabel(self.centralwidget)
        self.l2.setGeometry(QtCore.QRect(510, 70, 571, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.l2.setFont(font)
        self.l2.setObjectName("l2")
        self.l3 = QtWidgets.QLabel(self.centralwidget)
        self.l3.setGeometry(QtCore.QRect(100, 140, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.l3.setFont(font)
        self.l3.setObjectName("l3")
        self.l4 = QtWidgets.QLabel(self.centralwidget)
        self.l4.setGeometry(QtCore.QRect(510, 150, 581, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.l4.setFont(font)
        self.l4.setObjectName("l4")
        self.l5 = QtWidgets.QLabel(self.centralwidget)
        self.l5.setGeometry(QtCore.QRect(100, 230, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.l5.setFont(font)
        self.l5.setObjectName("l5")
        self.l6 = QtWidgets.QLabel(self.centralwidget)
        self.l6.setGeometry(QtCore.QRect(100, 330, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.l6.setFont(font)
        self.l6.setObjectName("l6")
        self.t1 = QtWidgets.QLineEdit(self.centralwidget)
        self.t1.setGeometry(QtCore.QRect(510, 240, 591, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.t1.setFont(font)
        self.t1.setObjectName("t1")
        self.t2 = QtWidgets.QLineEdit(self.centralwidget)
        self.t2.setGeometry(QtCore.QRect(510, 330, 591, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.t2.setFont(font)
        self.t2.setObjectName("t2")
        self.b1 = QtWidgets.QPushButton(self.centralwidget)
        self.b1.setGeometry(QtCore.QRect(430, 450, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.b1.setFont(font)
        self.b1.setObjectName("b1")

        self.b1.clicked.connect(self.add)

        pescribe.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(pescribe)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1117, 26))
        self.menubar.setObjectName("menubar")
        pescribe.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(pescribe)
        self.statusbar.setObjectName("statusbar")
        pescribe.setStatusBar(self.statusbar)

        

        self.retranslateUi(pescribe)
        QtCore.QMetaObject.connectSlotsByName(pescribe)
        self.show()

    def retranslateUi(self, pescribe):
        _translate = QtCore.QCoreApplication.translate
        pescribe.setWindowTitle(_translate("pescribe", "MainWindow"))
        self.l1.setText(_translate("pescribe", "Patient Name"))
        self.l2.setText(_translate("pescribe", ""))
        self.l3.setText(_translate("pescribe", "Symptom"))
        self.l4.setText(_translate("pescribe", ""))
        self.l5.setText(_translate("pescribe", "Medichine"))
        self.l6.setText(_translate("pescribe", "Remark"))
        self.b1.setText(_translate("pescribe", "ADD"))

    def add(self):
        import sqlite3
        conn = sqlite3.connect("dms.db")
        cur = conn.cursor()
        a= self.t1.text()
        b= self.t2.text()
        v=(a,b)
        sql = "select count(*) from pescribe where  medicine=? or remark=?"
        cur.execute(sql, v)
        c = cur.fetchall()

        conn.commit()
        
        if c == 0:

            sql="insert into pescribe values (?,?)"
            cur.execute(sql, v)
            c = cur.fetchall()

            conn.commit()
            msg = QMessageBox()
            msg.setIcon(QMessageBox.Critical)
            msg.setText("Add pescribe")
            msg.setWindowTitle("Add pescribe")
            msg.exec_()
        else:
            msg = QMessageBox()
            msg.setText("Not added")
            msg.exec_()
        conn.close()
        
    def show(self):
        import sqlite3
        conn = sqlite3.connect("dms.db")
        
        date=datetime.now()
        d=date.strftime("%d-%m-%Y")
        v1=(self.p,d)
        cur=conn.cursor()
        sql="select  * from booking where pid=? and date=?"
        res = cur.execute(sql,v1)
        r=res.fetchall()
        n=r[0][1]
        s=r[0][2]
        self.l2.setText(n)
        self.l4.setText(s)
        conn.close()
     


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    pescribe = QtWidgets.QMainWindow()
    ui = Ui_pescribe()
    ui.setupUi(pescribe)
    pescribe.show()
    sys.exit(app.exec_())
